-- Create table to track AI caption usage per user per day
CREATE TABLE IF NOT EXISTS public.ai_caption_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for efficient lookups
CREATE INDEX IF NOT EXISTS idx_ai_caption_usage_user_date 
  ON public.ai_caption_usage(user_id, created_at DESC);

-- Add RLS policies
ALTER TABLE public.ai_caption_usage ENABLE ROW LEVEL SECURITY;

-- Users can view their own usage
CREATE POLICY "Users can view their own AI caption usage"
  ON public.ai_caption_usage
  FOR SELECT
  USING (auth.uid() = user_id);

-- Admins can view all usage
CREATE POLICY "Admins can view all AI caption usage"
  ON public.ai_caption_usage
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.is_admin = true
    )
  );

-- Service role can insert/update (for the NM GUARD BETA service)
-- Note: Service role bypasses RLS, so this is just documentation
CREATE POLICY "Service can manage AI caption usage"
  ON public.ai_caption_usage
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Add comment for documentation
COMMENT ON TABLE public.ai_caption_usage IS 'Tracks AI caption generation usage for rate limiting. Managed by NM GUARD BETA service.';
COMMENT ON COLUMN public.ai_caption_usage.count IS 'Number of AI captions generated by this user on the date in created_at';
